/**
 * Append-only journal of forwarded tool calls (decision D-3).
 *
 * This is NOT document state. It is the ordered list of calls the relay
 * passed to the app, so that replaying it rebuilds everything the agent drew
 * after a lost tab. Because a command log is not a competing source of truth,
 * it introduces no sync problem — which is exactly why it was chosen over
 * having the relay hold the document.
 *
 * What it deliberately cannot see: the person's redlines. Those are drawn in
 * the tab and never travel through the relay, so they are OPFS's job on the
 * browser side. The journal covers the expensive half.
 */

import { appendFile, mkdir, readFile } from 'node:fs/promises';
import { dirname, join } from 'node:path';

/** One JSON object per line, so a partial write costs one entry, not the file. */
export class Journal {
  #dir;
  #seq = new Map(); // sessionId -> next sequence number

  constructor(dir) {
    this.#dir = dir;
  }

  #pathFor(sessionId) {
    // Session ids are generated by us from a fixed alphabet, but this path is
    // built from one anyway — reject anything that could climb out of the dir.
    if (!/^[A-Za-z0-9_-]{1,64}$/.test(sessionId)) {
      throw new Error(`refusing to build a journal path from ${JSON.stringify(sessionId)}`);
    }
    return join(this.#dir, `${sessionId}.jsonl`);
  }

  /** Record one forwarded call. Never throws into the request path — a
   *  journal write failing must not fail the drawing operation. */
  async record(sessionId, entry) {
    const n = (this.#seq.get(sessionId) ?? 0) + 1;
    this.#seq.set(sessionId, n);

    const line = JSON.stringify({ n, at: new Date().toISOString(), ...entry }) + '\n';
    try {
      const path = this.#pathFor(sessionId);
      await mkdir(dirname(path), { recursive: true });
      await appendFile(path, line, 'utf8');
    } catch (e) {
      console.error(`[journal] write failed for session ${sessionId}: ${e.message}`);
    }
    return n;
  }

  /** Read a session's journal back, for replay. Malformed lines are skipped
   *  rather than aborting the read — a truncated tail should not cost the
   *  whole session. */
  async read(sessionId) {
    let text;
    try {
      text = await readFile(this.#pathFor(sessionId), 'utf8');
    } catch (e) {
      if (e.code === 'ENOENT') return [];
      throw e;
    }
    const entries = [];
    for (const line of text.split('\n')) {
      if (!line.trim()) continue;
      try { entries.push(JSON.parse(line)); }
      catch { /* skip a torn line */ }
    }
    return entries;
  }

  /** The calls that actually changed the document, in order — what a replay
   *  would re-issue. Reads and view changes are noise for that purpose. */
  async replayable(sessionId) {
    const MUTATING = new Set([
      'app_new_blank_pdf', 'app_open_pdf', 'app_merge_pdf',
      'app_create_annotation', 'app_update_annotation', 'app_delete_annotation',
      'app_set_measure_scale', 'app_save_pdf',
    ]);
    const entries = await this.read(sessionId);
    return entries.filter((e) => e.ok !== false && MUTATING.has(e.tool));
  }
}
